# Generated by Django 5.1.3 on 2024-12-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='virtual_location',
        ),
    ]
