# Generated by Django 5.1.3 on 2024-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='stand',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
