# Generated by Django 5.1.3 on 2024-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_stand_coordinates_stand_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=50),
        ),
    ]
