# Generated by Django 5.1.3 on 2024-12-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_stand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_stands',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
