# Generated by Django 5.1.3 on 2024-12-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_stand_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stand',
            old_name='pdf',
            new_name='catalog_pdf',
        ),
        migrations.AddField(
            model_name='stand',
            name='prompts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
