# Generated by Django 5.1.3 on 2024-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_pdf_stand_catalog_pdf_stand_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='prompts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
