# Generated by Django 5.1.3 on 2024-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_stand_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='url_video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
