# Generated by Django 5.1.3 on 2024-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_stand_url_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='type',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=50),
        ),
    ]
