# Generated by Django 5.1.3 on 2025-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_stand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='url_web',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
