version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_app
    volumes:
      - .:/app  # Sincroniza tu código local con el contenedor
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al 8000 de tu máquina
