# Generated by Django 5.1.3 on 2024-12-11 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_score', models.IntegerField()),
                ('funnel_stage', models.CharField(max_length=50)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='events.stand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_seconds', models.IntegerField()),
                ('is_recurrent', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(max_length=50)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('interaction_details', models.TextField(blank=True, null=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='events.stand')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='interactions.visit')),
            ],
        ),
    ]
