# Generated by Django 5.1.3 on 2024-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='last_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
