# Generated by Django 5.1.3 on 2024-12-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_visit_last_entry_time_alter_visit_time_spent_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='last_entry_time',
        ),
    ]
