# Generated by Django 5.1.3 on 2024-12-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_interaction_interaction_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='interaction_details',
        ),
    ]
