# Generated by Django 5.1.3 on 2025-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_alter_interaction_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
